[package]
name = "rust-nes-emulator"
version = "0.1.0"
authors = ["K <kamiyaowl@gmail.com>"]
edition = "2018"

[features]
default = [ "unsafe-opt" ]
unsafe-opt = []

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true

[lib]
path = "src/lib.rs"
name = "rust_nes_emulator"