version: "3"
services:
    test:
      build: .
      volumes:
        - ./:/work
      command: cd test && cargo test
    test-release:
      build: .
      volumes:
        - ./:/work
      command: cd test && cargo test --release
    build-desktop:
      build: .
      volumes:
        - ./:/work
      command: cd desktop && cargo build
    build-desktop-release:
      build: .
      volumes:
        - ./:/work
      command: cd desktop && cargo build --release