# refer to https://www.ncaq.net/2019/03/08/21/12/35/
version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - run:
          name: Install Dependencies
          command: sudo apt install -y libgtk-3-dev
      - checkout
      - run: 
          name: Pull Submodule
          command: git submodule init && git submodule update --remote
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      # いまはまだformatもlintも気にしない
      # - run:
      #     name: fmt
      #     command: cargo fmt -- --check
      - run:
          name: build
          command: cargo build
      # - run:
      #     name: lint
      #     command: cargo clippy -- -D warnings
      - run:
          name: test
          command: cargo test -- --test-threads=1
          when: always
      - run:
          name: test ignored
          command: cargo test -- --test-threads=1 --ignored
          when: always
      - store_artifacts:
          path: test_run_hello_ppu.bmp
          destination: hello.bmp
      - store_artifacts:
          path: nestest_normal_menu.bmp
          destination: nestest_normal_menu.bmp
      - store_artifacts:
          path: nestest_normal.bmp
          destination: nestest_normal.bmp
      - store_artifacts:
          path: nestest_extra_menu.bmp
          destination: nestest_extra_menu.bmp
      - store_artifacts:
          path: nestest_extra.bmp
          destination: nestest_extra.bmp
      - run:
          name: build release
          command: cargo build --release
          when: always
      - run:
          name: test release
          command: cargo test --release -- --test-threads=1
          when: always
      - run:
          name: test release ignored
          command: cargo test --release -- --test-threads=1 --ignored
          when: always
      - store_artifacts:
          path: test_run_hello_ppu.bmp
          destination: release_hello.bmp
      - store_artifacts:
          path: nestest_normal_menu.bmp
          destination: release_nestest_normal_menu.bmp
      - store_artifacts:
          path: nestest_normal.bmp
          destination: release_nestest_normal.bmp
      - store_artifacts:
          path: nestest_extra_menu.bmp
          destination: release_nestest_extra_menu.bmp
      - store_artifacts:
          path: nestest_extra.bmp
          destination: release_nestest_extra.bmp
