# refer to https://www.ncaq.net/2019/03/08/21/12/35/
version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: 
          name: "Pull Submodule"
          command: git submodule init && git submodule update --remote
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      # いまはまだformatもlintも気にしない
      # - run:
      #     name: fmt
      #     command: cargo fmt -- --check
      - run:
          name: build
          command: cargo build
      # - run:
      #     name: lint
      #     command: cargo clippy -- -D warnings
      - run:
          name: test
          command: cargo test -- --test-threads=1
          when: always
      - run:
          name: test ignored
          command: cargo test -- --test-threads=1 --ignored
          when: always
      - store_artifacts:
          path: test_run_hello_ppu.bmp
          destination: hello_debug.bmp
      - store_artifacts:
          path: run_nestest_automation.log
          destination: run_nestest_automation_debug.log
      - store_artifacts:
          path: test_run_nestest_menu.bmp
          destination: nestest_menu_debug.bmp
      - run:
          name: build release
          command: cargo build --release
          when: always
      - run:
          name: test release
          command: cargo test --release -- --test-threads=1
          when: always
      - run:
          name: test release ignored
          command: cargo test --release -- --test-threads=1 --ignored
          when: always
      - store_artifacts:
          path: test_run_hello_ppu.bmp
          destination: hello_release.bmp
      - store_artifacts:
          path: run_nestest_automation.log
          destination: run_nestest_automation_release.log
      - store_artifacts:
          path: test_run_nestest_menu.bmp
          destination: nestest_menu_release.bmp
