# refer to https://www.ncaq.net/2019/03/08/21/12/35/
version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      # いまはまだformatもlintも気にしない
      # - run:
      #     name: fmt
      #     command: cargo fmt -- --check
      - run:
          name: build
          command: cargo build
      # - run:
      #     name: lint
      #     command: cargo clippy -- -D warnings
      - run:
          name: test
          command: cargo test
      - store_artifacts:
          path: framebuffer_run_hello_ppu.bmp
          destination: hello_debug.bmp
      - store_artifacts:
          path: framebuffer_nestest_boot.bmp
          destination: nestest_boot_debug.bmp
      - run:
          name: build release
          command: cargo build --release
      - run:
          name: test release
          command: cargo test --release
      - store_artifacts:
          path: framebuffer_run_hello_ppu.bmp
          destination: hello_release.bmp
