version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      # build dependencies
      - run:
          name: Install apt dependencies
          command: sudo apt install -y libgtk-3-dev nodejs npm
      - run:
          name: Install nodejs
          command: sudo npm install -g n && sudo n latest
      # code checkout
      - checkout
      - run: 
          name: Pull Submodule
          command: git submodule init && git submodule update --remote
      # install rustup and tools
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      - run:
          name: cargo install
          command: cargo install wasm-pack
      # build lib
      - run:
          name: build
          command: cargo build
          when: always
      - run:
          name: build release
          command: cargo build --release
          when: always
      # run test
      - run:
          name: test
          command: cd test && cargo test
          when: always
      - run:
          name: test release
          command: cd test && cargo test --release
          when: always
      # build desktop
      - run:
          name: build desktop
          command: cd desktop && cargo build
          when: always
      - run:
          name: build desktop release
          command: cd desktop && cargo build --release
          when: always
      # build wasm
    #   - run:
    #       name: build wasm
    #       command: cd wasm && wasm-pack build
    #       when: always
      - run:
          name: build wasm release
          command: cd wasm && wasm-pack build --release
          when: always
      # deploy to netlify
      - run:
          name: Install netlify-cli
          command: sudo npm install -g netlify-cli
      - run:
          name: Deploy to netlify
          command: netlify deploy --site-id $NETLIFY_SITE_ID -p ./wasm --access-token $NETLIFY_TOKEN

