# refer to https://www.ncaq.net/2019/03/08/21/12/35/
version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - run:
          name: Install Dependencies
          command: sudo apt install -y libgtk-3-dev
      - checkout
      - run: 
          name: Pull Submodule
          command: git submodule init && git submodule update --remote
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      # debug build and test
      - run:
          name: build
          command: cargo build
      - run:
          name: build desktop
          command: cd desktop && cargo build
      - run:
          name: test
          command: cd test && cargo test
          when: always
      # release build and test
      - run:
          name: build release
          command: cargo build --release
          when: always
      - run:
          name: build desktop release
          command: cd desktop && cargo build --release
          when: always
      - run:
          name: test release
          command: cd test && cargo test --release
          when: always
